-- Table: USA.natalityConf

-- DROP TABLE IF EXISTS "USA"."natalityConf";

CREATE TABLE IF NOT EXISTS "USA"."natalityConf"
(
    dt_year smallint,
    id_state character(2) COLLATE pg_catalog."default",
    id_area character(1) COLLATE pg_catalog."default",
    id_cert character(6) COLLATE pg_catalog."default",
    in_resident character(1) COLLATE pg_catalog."default",
    id_res_status character(1) COLLATE pg_catalog."default",
    id_residence character(15) COLLATE pg_catalog."default",
    id_occurence character(17) COLLATE pg_catalog."default",
    id_sex character(1) COLLATE pg_catalog."default",
    id_attendant character(1) COLLATE pg_catalog."default",
    id_f_race character(1) COLLATE pg_catalog."default",
    id_m_race character(1) COLLATE pg_catalog."default",
    id_c_race character(1) COLLATE pg_catalog."default",
    id_c_race3 character(1) COLLATE pg_catalog."default",
    am_m_age character(2) COLLATE pg_catalog."default",
    am_m_age36 character(2) COLLATE pg_catalog."default",
    am_m_age15 character(2) COLLATE pg_catalog."default",
    am_m_age12 character(2) COLLATE pg_catalog."default",
    am_m_age8 character(1) COLLATE pg_catalog."default",
    am_m_age7 character(1) COLLATE pg_catalog."default",
    am_m_age6 character(1) COLLATE pg_catalog."default",
    am_children_basl character(2) COLLATE pg_catalog."default",
    am_children_band character(2) COLLATE pg_catalog."default",
    am_children_bd character(2) COLLATE pg_catalog."default",
    am_tot_b_order character(2) COLLATE pg_catalog."default",
    am_tot_b_order9 character(1) COLLATE pg_catalog."default",
    am_live_b_order character(1) COLLATE pg_catalog."default",
    am_live_b_order9 character(1) COLLATE pg_catalog."default",
    am_live_b_order8 character(1) COLLATE pg_catalog."default",
    am_live_b_order7 character(1) COLLATE pg_catalog."default",
    am_live_b_order6 character(1) COLLATE pg_catalog."default",
    am_live_b_order3 character(1) COLLATE pg_catalog."default",
    reserved character(1) COLLATE pg_catalog."default",
    am_f_age character(2) COLLATE pg_catalog."default",
    am_f_age11 character(2) COLLATE pg_catalog."default",
    am_birthweight character(4) COLLATE pg_catalog."default",
    am_birthweight12 character(2) COLLATE pg_catalog."default",
    am_birthweight3 character(1) COLLATE pg_catalog."default",
    id_delivery_loc character(1) COLLATE pg_catalog."default",
    am_plurality character(1) COLLATE pg_catalog."default",
    am_plurality3 character(1) COLLATE pg_catalog."default",
    am_plurality2 character(1) COLLATE pg_catalog."default",
    dt_birth_mmdd character(4) COLLATE pg_catalog."default",
    dt_last_menses character(5) COLLATE pg_catalog."default",
    am_gestation character(2) COLLATE pg_catalog."default",
    am_gestation10 character(2) COLLATE pg_catalog."default",
    am_gestation3 character(1) COLLATE pg_catalog."default",
    id_m_edu character(2) COLLATE pg_catalog."default",
    id_m_edu14 character(2) COLLATE pg_catalog."default",
    id_m_edu6 character(1) COLLATE pg_catalog."default",
    id_f_edu character(2) COLLATE pg_catalog."default",
    id_f_edu14 character(2) COLLATE pg_catalog."default",
    in_married character(1) COLLATE pg_catalog."default",
    in_married2 character(1) COLLATE pg_catalog."default",
    am_prenatal character(1) COLLATE pg_catalog."default",
    am_prenatal10 character(2) COLLATE pg_catalog."default",
    am_prenatal6 character(1) COLLATE pg_catalog."default",
    dt_last_lb_mm19yy character(4) COLLATE pg_catalog."default",
    am_post_last_lb character(3) COLLATE pg_catalog."default",
    am_post_last_lb17 character(2) COLLATE pg_catalog."default",
    am_post_last_lb10 character(2) COLLATE pg_catalog."default",
    am_post_last_lb8 character(1) COLLATE pg_catalog."default",
    dt_last_termin character(4) COLLATE pg_catalog."default",
    in_last_termin character(1) COLLATE pg_catalog."default",
    am_post_lt character(3) COLLATE pg_catalog."default",
    am_post_tlp character(3) COLLATE pg_catalog."default",
    am_post_tlp9 character(1) COLLATE pg_catalog."default",
    id_last_preg character(1) COLLATE pg_catalog."default",
    id_m_birthplace character(2) COLLATE pg_catalog."default",
    am_tot_prenatal character(2) COLLATE pg_catalog."default",
    in_malformation character(1) COLLATE pg_catalog."default",
    reserved2 character(3) COLLATE pg_catalog."default",
    in_report_flags character(15) COLLATE pg_catalog."default",
    in_occur_flags character(12) COLLATE pg_catalog."default",
    reserved3 character(3) COLLATE pg_catalog."default",
    id_attendant_nchs character(1) COLLATE pg_catalog."default",
    am_terminationlt20 character(2) COLLATE pg_catalog."default",
    am_terminationgt20 character(2) COLLATE pg_catalog."default",
    am_1min_apgar character(2) COLLATE pg_catalog."default",
    am_1min_apgar5 character(1) COLLATE pg_catalog."default",
    am_5min_apgar character(2) COLLATE pg_catalog."default",
    am_5min_apgar5 character(1) COLLATE pg_catalog."default",
    id_m_descent character(2) COLLATE pg_catalog."default",
    id_f_descent character(2) COLLATE pg_catalog."default",
    in_gest_flag character(1) COLLATE pg_catalog."default",
    id_res_region character(1) COLLATE pg_catalog."default",
    id_occ_region character(1) COLLATE pg_catalog."default",
    id_fips_occ character(14) COLLATE pg_catalog."default",
    id_weight_rec character(1) COLLATE pg_catalog."default",
    am_prenatal28 character(2) COLLATE pg_catalog."default",
    am_prenatal12 character(2) COLLATE pg_catalog."default",
    reserved4 character(1) COLLATE pg_catalog."default",
    id_state_occ character(2) COLLATE pg_catalog."default",
    am_post_full_con smallint,
    am_lunar_month_con smallint,
    dt_conception date,
    am_post_full_dob smallint,
    am_lunar_month_dob smallint,
    dt_dob date,
    id integer,
    state character varying(50) COLLATE pg_catalog."default",
    county character varying(50) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "USA"."natalityConf"
    OWNER to postgres;